/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package itec;

import java.io.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author cosmin
 */
public class MyTables extends javax.swing.JFrame {
    

    /**
     * Creates new form MyTables
     */
    DataBaseConnection conn;
    Object[][] rep = null;
    Object[][] rep2 = null;
    
    
    public MyTables() {
        initComponents();
        conn = new DataBaseConnection();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
           conn.getReport(),
            new String [] {
                "id", "User Name", "Product", "Points", "Date"
            }
        ));
        jTable1.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setLocationByPlatform(true);
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "User Name", "Product", "Points", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("itec/Bundle"); // NOI18N
        jMenu1.setText(bundle.getString("MyTables.jMenu1.text")); // NOI18N

        jMenuItem1.setText(bundle.getString("MyTables.jMenuItem1.text")); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //scriu intr-un fisier xls
       int buget = 0;
       buget = Integer.parseInt(JOptionPane.showInputDialog(this,"Ce buget alocati ?"));
       Object[] itemsFromDataBase = conn.getItems();
       Object[][] itemsFromVotes = conn.getReport();
       int sumPoints = 0,count = 0,i = 0;
       rep = new Object[itemsFromDataBase.length][4];
       double budget = 0;
       for(int y=0;y<itemsFromDataBase.length;y++){
          for(int z = 0; z<itemsFromVotes.length;z++){
              if(itemsFromDataBase[y].equals(itemsFromVotes[z][2])){
                  ++count;
                  sumPoints += Integer.parseInt((String) itemsFromVotes[z][3]); 
              }
           }
          rep[y][0] = itemsFromDataBase[y];
          rep[y][1] = count;
          count = 0;
          rep[y][2] = sumPoints;
          budget = (sumPoints*buget)/100;
          sumPoints = 0;
          rep[y][3] = budget;           //obtain the individual budget
          
         
       } 
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
           rep,
            new String [] {
                "Product", "Votes", "Points", "Budget"
            }
        ));
        jTable1.setEnabled(false);
        rep2 = new Object[(rep.length)+4][4];
       
        rep2[0][0] = "Product";
        rep2[0][1] = "Votes";
        rep2[0][2] = "Points";
        rep2[0][3] = "Budget";
        
        for(int k = 1;k<rep.length;k++)
        {
            rep2[k][0] = rep[k][0];
            rep2[k][1] = rep[k][1];
            rep2[k][2] = rep[k][2];
            rep2[k][3] = rep[k][3];
        }
        WriteXls xls = new WriteXls();
        try{
        JFileChooser saveFile  = new JFileChooser();
        saveFile.addChoosableFileFilter(new FileFilter()
        {
           String description = "Microsoft Excel(*.xls)";
           String extension = "xls";
           
           public String getDescription(){
               return description;
           }
           
           @Override
           public boolean accept(File f){
              if(f == null)
               return false;
              if(f.isDirectory())
                  return true;
              return f.getName().toLowerCase().endsWith(extension);
           }
            
        });
        saveFile.setCurrentDirectory(new File(".*xls"));
        int sel = saveFile.showSaveDialog(this);
        String fileName = saveFile.getSelectedFile().getName();
        xls.writeData(rep2, fileName);
        }catch(Exception exc){
            exc.printStackTrace();
        } 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

   
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
